services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-bigquery:1.7.0
    container_name: dbt-bigquery
    volumes:
      - ./:/usr/app
      - ./profiles.yml:/root/.dbt/profiles.yml
      - ./gcp-creds:/root/.config/gcloud:ro
    working_dir: /usr/app/taxi_rides_ny
    environment:
      DBT_PROFILES_DIR: /usr/app
    entrypoint: ["sleep", "infinity"]