taxi_rides_ny:
  outputs:
    dev:
      dataset: zoomcamp
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-west3
      method: oauth
      priority: interactive
      project: vital-plating-485118-d8
      threads: 4
      type: bigquery
  target: dev
